INSERT INTO language(name) VALUES ('Afar');
INSERT INTO language(name) VALUES ('Abkhazian');
INSERT INTO language(name) VALUES ('Afrikaans');
INSERT INTO language(name) VALUES ('Akan');
INSERT INTO language(name) VALUES ('Alemannic');
INSERT INTO language(name) VALUES ('Amharic');
INSERT INTO language(name) VALUES ('Aragonese');
INSERT INTO language(name) VALUES ('Anglo-Saxon');
INSERT INTO language(name) VALUES ('Arabic');
INSERT INTO language(name) VALUES ('Aramaic');
INSERT INTO language(name) VALUES ('Assamese');
INSERT INTO language(name) VALUES ('Asturian');
INSERT INTO language(name) VALUES ('Avar');
INSERT INTO language(name) VALUES ('Aymara');
INSERT INTO language(name) VALUES ('Azerbaijani');
INSERT INTO language(name) VALUES ('Bashkir');
INSERT INTO language(name) VALUES ('Bavarian');
INSERT INTO language(name) VALUES ('Samogitian');
INSERT INTO language(name) VALUES ('Bikol');
INSERT INTO language(name) VALUES ('Belarusian');
INSERT INTO language(name) VALUES ('Bulgarian');
INSERT INTO language(name) VALUES ('Bihari');
INSERT INTO language(name) VALUES ('Bislama');
INSERT INTO language(name) VALUES ('Bambara');
INSERT INTO language(name) VALUES ('Bengali');
INSERT INTO language(name) VALUES ('Tibetan');
INSERT INTO language(name) VALUES ('Bishnupriya Manipuri');
INSERT INTO language(name) VALUES ('Breton');
INSERT INTO language(name) VALUES ('Bosnian');
INSERT INTO language(name) VALUES ('Buginese');
INSERT INTO language(name) VALUES ('Buriat (Russia)');
INSERT INTO language(name) VALUES ('Catalan');
INSERT INTO language(name) VALUES ('Min Dong Chinese');
INSERT INTO language(name) VALUES ('Chechen');
INSERT INTO language(name) VALUES ('Cebuano');
INSERT INTO language(name) VALUES ('Chamorro');
INSERT INTO language(name) VALUES ('Choctaw');
INSERT INTO language(name) VALUES ('Cherokee');
INSERT INTO language(name) VALUES ('Cheyenne');
INSERT INTO language(name) VALUES ('Corsican');
INSERT INTO language(name) VALUES ('Cree');
INSERT INTO language(name) VALUES ('Czech');
INSERT INTO language(name) VALUES ('Kashubian');
INSERT INTO language(name) VALUES ('Chuvash');
INSERT INTO language(name) VALUES ('Welsh');
INSERT INTO language(name) VALUES ('Danish');
INSERT INTO language(name) VALUES ('German');
INSERT INTO language(name) VALUES ('Dimli');
INSERT INTO language(name) VALUES ('Lower Sorbian');
INSERT INTO language(name) VALUES ('Divehi');
INSERT INTO language(name) VALUES ('Dzongkha');
INSERT INTO language(name) VALUES ('Ewe');
INSERT INTO language(name) VALUES ('Greek');
INSERT INTO language(name) VALUES ('English');
INSERT INTO language(name) VALUES ('Esperanto');
INSERT INTO language(name) VALUES ('Spanish');
INSERT INTO language(name) VALUES ('Estonian');
INSERT INTO language(name) VALUES ('Basque');
INSERT INTO language(name) VALUES ('Extremaduran');
INSERT INTO language(name) VALUES ('Persian');
INSERT INTO language(name) VALUES ('Peul');
INSERT INTO language(name) VALUES ('Finnish');
INSERT INTO language(name) VALUES ('Võro');
INSERT INTO language(name) VALUES ('Fijian');
INSERT INTO language(name) VALUES ('Faroese');
INSERT INTO language(name) VALUES ('French');
INSERT INTO language(name) VALUES ('Friulian');
INSERT INTO language(name) VALUES ('West Frisian');
INSERT INTO language(name) VALUES ('Irish');
INSERT INTO language(name) VALUES ('Gan Chinese');
INSERT INTO language(name) VALUES ('Garhwali');
INSERT INTO language(name) VALUES ('Scottish Gaelic');
INSERT INTO language(name) VALUES ('Gilbertese');
INSERT INTO language(name) VALUES ('Galician');
INSERT INTO language(name) VALUES ('Guarani');
INSERT INTO language(name) VALUES ('Gothic');
INSERT INTO language(name) VALUES ('Gujarati');
INSERT INTO language(name) VALUES ('Manx');
INSERT INTO language(name) VALUES ('Hausa');
INSERT INTO language(name) VALUES ('Hakka Chinese');
INSERT INTO language(name) VALUES ('Hawaiian');
INSERT INTO language(name) VALUES ('Hebrew');
INSERT INTO language(name) VALUES ('Hindi');
INSERT INTO language(name) VALUES ('Hiri Motu');
INSERT INTO language(name) VALUES ('Croatian');
INSERT INTO language(name) VALUES ('Haitian');
INSERT INTO language(name) VALUES ('Hungarian');
INSERT INTO language(name) VALUES ('Armenian');
INSERT INTO language(name) VALUES ('Herero');
INSERT INTO language(name) VALUES ('Interlingua');
INSERT INTO language(name) VALUES ('Indonesian');
INSERT INTO language(name) VALUES ('Interlingue');
INSERT INTO language(name) VALUES ('Igbo');
INSERT INTO language(name) VALUES ('Sichuan Yi');
INSERT INTO language(name) VALUES ('Inupiak');
INSERT INTO language(name) VALUES ('Ilokano');
INSERT INTO language(name) VALUES ('Ingush');
INSERT INTO language(name) VALUES ('Ido');
INSERT INTO language(name) VALUES ('Icelandic');
INSERT INTO language(name) VALUES ('Italian');
INSERT INTO language(name) VALUES ('Inuktitut');
INSERT INTO language(name) VALUES ('Japanese');
INSERT INTO language(name) VALUES ('Lojban');
INSERT INTO language(name) VALUES ('Javanese');
INSERT INTO language(name) VALUES ('Georgian');
INSERT INTO language(name) VALUES ('Kongo');
INSERT INTO language(name) VALUES ('Kikuyu');
INSERT INTO language(name) VALUES ('Kuanyama');
INSERT INTO language(name) VALUES ('Kazakh');
INSERT INTO language(name) VALUES ('Greenlandic');
INSERT INTO language(name) VALUES ('Cambodian');
INSERT INTO language(name) VALUES ('Kannada');
INSERT INTO language(name) VALUES ('Khowar');
INSERT INTO language(name) VALUES ('Korean');
INSERT INTO language(name) VALUES ('Kanuri');
INSERT INTO language(name) VALUES ('Kashmiri');
INSERT INTO language(name) VALUES ('Ripuarian');
INSERT INTO language(name) VALUES ('Kurdish');
INSERT INTO language(name) VALUES ('Komi');
INSERT INTO language(name) VALUES ('Cornish');
INSERT INTO language(name) VALUES ('Kirghiz');
INSERT INTO language(name) VALUES ('Latin');
INSERT INTO language(name) VALUES ('Lango');
INSERT INTO language(name) VALUES ('Luxembourgish');
INSERT INTO language(name) VALUES ('Ganda');
INSERT INTO language(name) VALUES ('Limburgian');
INSERT INTO language(name) VALUES ('Ligurian');
INSERT INTO language(name) VALUES ('Lombard');
INSERT INTO language(name) VALUES ('Lingala');
INSERT INTO language(name) VALUES ('Laotian');
INSERT INTO language(name) VALUES ('Laz');
INSERT INTO language(name) VALUES ('Lithuanian');
INSERT INTO language(name) VALUES ('Latvian');
INSERT INTO language(name) VALUES ('Banyumasan');
INSERT INTO language(name) VALUES ('Malagasy');
INSERT INTO language(name) VALUES ('Mandarin');
INSERT INTO language(name) VALUES ('Marshallese');
INSERT INTO language(name) VALUES ('Maori');
INSERT INTO language(name) VALUES ('Minangkabau');
INSERT INTO language(name) VALUES ('Macedonian');
INSERT INTO language(name) VALUES ('Malayalam');
INSERT INTO language(name) VALUES ('Mongolian');
INSERT INTO language(name) VALUES ('Moldovan');
INSERT INTO language(name) VALUES ('Marathi');
INSERT INTO language(name) VALUES ('Malay');
INSERT INTO language(name) VALUES ('Maltese');
INSERT INTO language(name) VALUES ('Creek / Muskogee');
INSERT INTO language(name) VALUES ('Mirandese');
INSERT INTO language(name) VALUES ('Burmese');
INSERT INTO language(name) VALUES ('Nauruan');
INSERT INTO language(name) VALUES ('Nahuatl');
INSERT INTO language(name) VALUES ('Neapolitan');
INSERT INTO language(name) VALUES ('North Ndebele');
INSERT INTO language(name) VALUES ('Dutch Low Saxon');
INSERT INTO language(name) VALUES ('Nepali');
INSERT INTO language(name) VALUES ('Newar');
INSERT INTO language(name) VALUES ('Ndonga');
INSERT INTO language(name) VALUES ('Dutch');
INSERT INTO language(name) VALUES ('Norwegian Nynorsk');
INSERT INTO language(name) VALUES ('Norwegian');
INSERT INTO language(name) VALUES ('South Ndebele');
INSERT INTO language(name) VALUES ('Northern Sotho');
INSERT INTO language(name) VALUES ('Norman');
INSERT INTO language(name) VALUES ('Navajo');
INSERT INTO language(name) VALUES ('Chichewa');
INSERT INTO language(name) VALUES ('Occitan');
INSERT INTO language(name) VALUES ('Ojibwa');
INSERT INTO language(name) VALUES ('Oromo');
INSERT INTO language(name) VALUES ('Oriya');
INSERT INTO language(name) VALUES ('Ossetian / Ossetic');
INSERT INTO language(name) VALUES ('Panjabi / Punjabi');
INSERT INTO language(name) VALUES ('Pangasinan');
INSERT INTO language(name) VALUES ('Kapampangan');
INSERT INTO language(name) VALUES ('Papiamentu');
INSERT INTO language(name) VALUES ('Pennsylvania German');
INSERT INTO language(name) VALUES ('Pali');
INSERT INTO language(name) VALUES ('Norfolk');
INSERT INTO language(name) VALUES ('Polish');
INSERT INTO language(name) VALUES ('Piedmontese');
INSERT INTO language(name) VALUES ('Pashto');
INSERT INTO language(name) VALUES ('Portuguese');
INSERT INTO language(name) VALUES ('Quechua');
INSERT INTO language(name) VALUES ('Raeto Romance');
INSERT INTO language(name) VALUES ('Romani');
INSERT INTO language(name) VALUES ('Kirundi');
INSERT INTO language(name) VALUES ('Romanian');
INSERT INTO language(name) VALUES ('Aromanian');
INSERT INTO language(name) VALUES ('Russian');
INSERT INTO language(name) VALUES ('Rwandi');
INSERT INTO language(name) VALUES ('Sanskrit');
INSERT INTO language(name) VALUES ('Sardinian');
INSERT INTO language(name) VALUES ('Sicilian');
INSERT INTO language(name) VALUES ('Scots');
INSERT INTO language(name) VALUES ('Sindhi');
INSERT INTO language(name) VALUES ('Northern Sami');
INSERT INTO language(name) VALUES ('Sango');
INSERT INTO language(name) VALUES ('Serbo-Croatian');
INSERT INTO language(name) VALUES ('Sinhalese');
INSERT INTO language(name) VALUES ('Simple English');
INSERT INTO language(name) VALUES ('Slovak');
INSERT INTO language(name) VALUES ('Slovenian');
INSERT INTO language(name) VALUES ('Samoan');
INSERT INTO language(name) VALUES ('Shona');
INSERT INTO language(name) VALUES ('Somalia');
INSERT INTO language(name) VALUES ('Albanian');
INSERT INTO language(name) VALUES ('Serbian');
INSERT INTO language(name) VALUES ('Swati');
INSERT INTO language(name) VALUES ('Southern Sotho');
INSERT INTO language(name) VALUES ('Sundanese');
INSERT INTO language(name) VALUES ('Swedish');
INSERT INTO language(name) VALUES ('Swahili');
INSERT INTO language(name) VALUES ('Tamil');
INSERT INTO language(name) VALUES ('Telugu');
INSERT INTO language(name) VALUES ('Tetum');
INSERT INTO language(name) VALUES ('Tajik');
INSERT INTO language(name) VALUES ('Thai');
INSERT INTO language(name) VALUES ('Tigrinya');
INSERT INTO language(name) VALUES ('Turkmen');
INSERT INTO language(name) VALUES ('Tagalog');
INSERT INTO language(name) VALUES ('Klingon');
INSERT INTO language(name) VALUES ('Tswana');
INSERT INTO language(name) VALUES ('Tonga');
INSERT INTO language(name) VALUES ('Tok Pisin');
INSERT INTO language(name) VALUES ('Turkish');
INSERT INTO language(name) VALUES ('Tsonga');
INSERT INTO language(name) VALUES ('Tatar');
INSERT INTO language(name) VALUES ('Tumbuka');
INSERT INTO language(name) VALUES ('Twi');
INSERT INTO language(name) VALUES ('Tahitian');
INSERT INTO language(name) VALUES ('Udmurt');
INSERT INTO language(name) VALUES ('Uyghur');
INSERT INTO language(name) VALUES ('Ukrainian');
INSERT INTO language(name) VALUES ('Urdu');
INSERT INTO language(name) VALUES ('Uzbek');
INSERT INTO language(name) VALUES ('Venda');
INSERT INTO language(name) VALUES ('Vietnamese');
INSERT INTO language(name) VALUES ('Venetian');
INSERT INTO language(name) VALUES ('West Flemish');
INSERT INTO language(name) VALUES ('Volapük');
INSERT INTO language(name) VALUES ('Walloon');
INSERT INTO language(name) VALUES ('Wolof');
INSERT INTO language(name) VALUES ('Kalmyk');
INSERT INTO language(name) VALUES ('Xhosa');
INSERT INTO language(name) VALUES ('Megrelian');
INSERT INTO language(name) VALUES ('Yiddish');
INSERT INTO language(name) VALUES ('Yoruba');
INSERT INTO language(name) VALUES ('Zhuang');
INSERT INTO language(name) VALUES ('Chinese');
INSERT INTO language(name) VALUES ('Classical Chinese');
INSERT INTO language(name) VALUES ('Minnan');
INSERT INTO language(name) VALUES ('Cantonese');
INSERT INTO language(name) VALUES ('Zulu');
