INSERT INTO publisher(name,royalty) VALUES ('Ablex Publishing',5789);
INSERT INTO publisher(name,royalty) VALUES ('Academic Press',2011);
INSERT INTO publisher(name,royalty) VALUES ('Ace Books',5258);
INSERT INTO publisher(name,royalty) VALUES ('Adis International',7894);
INSERT INTO publisher(name,royalty) VALUES ('Airiti Press',220);
INSERT INTO publisher(name,royalty) VALUES ('Akashic Books',6545);
INSERT INTO publisher(name,royalty) VALUES ('Aladdin Paperbacks',9331);
INSERT INTO publisher(name,royalty) VALUES ('Alyson Books',1408);
INSERT INTO publisher(name,royalty) VALUES ('Anova Books',4595);
INSERT INTO publisher(name,royalty) VALUES ('Antenne Books',8676);
INSERT INTO publisher(name,royalty) VALUES ('Applewood Books',3939);
INSERT INTO publisher(name,royalty) VALUES ('Apress',6918);
INSERT INTO publisher(name,royalty) VALUES ('Arbor House',2077);
INSERT INTO publisher(name,royalty) VALUES ('Arbordale Publishing',1622);
INSERT INTO publisher(name,royalty) VALUES ('Arcade Publishing',6932);
INSERT INTO publisher(name,royalty) VALUES ('Arcadia Publishing',4476);
INSERT INTO publisher(name,royalty) VALUES ('Arkham House',6707);
INSERT INTO publisher(name,royalty) VALUES ('Arktos Media',1399);
INSERT INTO publisher(name,royalty) VALUES ('Armida Publications',9390);
INSERT INTO publisher(name,royalty) VALUES ('Atheneum Books',312);
INSERT INTO publisher(name,royalty) VALUES ('Atheneum Publishers',1553);
INSERT INTO publisher(name,royalty) VALUES ('Atlantic Books',4307);
INSERT INTO publisher(name,royalty) VALUES ('Atlas Press',89);
INSERT INTO publisher(name,royalty) VALUES ('Atria',1034);
INSERT INTO publisher(name,royalty) VALUES ('Augsburg Fortress',1695);
INSERT INTO publisher(name,royalty) VALUES ('Avery Publishing',9287);
INSERT INTO publisher(name,royalty) VALUES ('Avon Publications',9219);
INSERT INTO publisher(name,royalty) VALUES ('Baen Books',2034);
INSERT INTO publisher(name,royalty) VALUES ('Ballantine Books',3263);
INSERT INTO publisher(name,royalty) VALUES ('Bantam Books',1875);
INSERT INTO publisher(name,royalty) VALUES ('Bantam Spectra',6700);
INSERT INTO publisher(name,royalty) VALUES ('Basic Books',302);
INSERT INTO publisher(name,royalty) VALUES ('Belknap Press',8997);
INSERT INTO publisher(name,royalty) VALUES ('Bella Books',4465);
INSERT INTO publisher(name,royalty) VALUES ('Berg Publishers',611);
INSERT INTO publisher(name,royalty) VALUES ('Berkley Books',3622);
INSERT INTO publisher(name,royalty) VALUES ('Bison Books',3481);
INSERT INTO publisher(name,royalty) VALUES ('Black Library',377);
INSERT INTO publisher(name,royalty) VALUES ('Blackstaff Press',5317);
INSERT INTO publisher(name,royalty) VALUES ('Blackwell Publishing',1817);
INSERT INTO publisher(name,royalty) VALUES ('Blake Publishing',9557);
INSERT INTO publisher(name,royalty) VALUES ('Bloodaxe Books',8594);
INSERT INTO publisher(name,royalty) VALUES ('Book Works',1374);
INSERT INTO publisher(name,royalty) VALUES ('Booktrope',6892);
INSERT INTO publisher(name,royalty) VALUES ('Borgo Press',2189);
INSERT INTO publisher(name,royalty) VALUES ('Boundless',6815);
INSERT INTO publisher(name,royalty) VALUES ('Brill Publishers',6274);
INSERT INTO publisher(name,royalty) VALUES ('Brimstone Press',5834);
INSERT INTO publisher(name,royalty) VALUES ('Broadview Press',2059);
INSERT INTO publisher(name,royalty) VALUES ('Candlewick Press',6815);
INSERT INTO publisher(name,royalty) VALUES ('Canongate Books',2992);
INSERT INTO publisher(name,royalty) VALUES ('Capstone Publishers',1314);
INSERT INTO publisher(name,royalty) VALUES ('Carcanet Press',6876);
INSERT INTO publisher(name,royalty) VALUES ('Carlton Books',761);
INSERT INTO publisher(name,royalty) VALUES ('Casemate Publishers',14);
INSERT INTO publisher(name,royalty) VALUES ('Cassell',7517);
INSERT INTO publisher(name,royalty) VALUES ('Cengage Learning',7717);
INSERT INTO publisher(name,royalty) VALUES ('Century',8074);
INSERT INTO publisher(name,royalty) VALUES ('Chambers Harrap',7176);
INSERT INTO publisher(name,royalty) VALUES ('Chick Publications',6319);
INSERT INTO publisher(name,royalty) VALUES ('Chronicle Books',1308);
INSERT INTO publisher(name,royalty) VALUES ('Churchill Livingstone',2878);
INSERT INTO publisher(name,royalty) VALUES ('Cisco Press',6592);
INSERT INTO publisher(name,royalty) VALUES ('Cloverdale Corporation',7745);
INSERT INTO publisher(name,royalty) VALUES ('Collins',6871);
INSERT INTO publisher(name,royalty) VALUES ('Coronet Books',1285);
INSERT INTO publisher(name,royalty) VALUES ('Cresset Press',458);
INSERT INTO publisher(name,royalty) VALUES ('Dedalus Books',4059);
INSERT INTO publisher(name,royalty) VALUES ('Delacorte Press',7749);
INSERT INTO publisher(name,royalty) VALUES ('Deseret Book',368);
INSERT INTO publisher(name,royalty) VALUES ('Directmedia Publishing',1091);
INSERT INTO publisher(name,royalty) VALUES ('Dobson Books',5777);
INSERT INTO publisher(name,royalty) VALUES ('Dorchester Publishing',653);
INSERT INTO publisher(name,royalty) VALUES ('Dorling Kindersley',4293);
INSERT INTO publisher(name,royalty) VALUES ('Doubleday',2696);
INSERT INTO publisher(name,royalty) VALUES ('Dover Publications',4228);
INSERT INTO publisher(name,royalty) VALUES ('Dundurn Group',3084);
INSERT INTO publisher(name,royalty) VALUES ('Earthscan',2879);
INSERT INTO publisher(name,royalty) VALUES ('Eerdmans Publishing',9402);
INSERT INTO publisher(name,royalty) VALUES ('Elliot Stock',6421);
INSERT INTO publisher(name,royalty) VALUES ('Elsevier',3284);
INSERT INTO publisher(name,royalty) VALUES ('Etruscan Press',605);
INSERT INTO publisher(name,royalty) VALUES ('Europa Press',3872);
INSERT INTO publisher(name,royalty) VALUES ('Exact Change',203);
INSERT INTO publisher(name,royalty) VALUES ('Express Publishing',3719);
INSERT INTO publisher(name,royalty) VALUES ('Fairview Press',9194);
INSERT INTO publisher(name,royalty) VALUES ('Fearless Books',2123);
INSERT INTO publisher(name,royalty) VALUES ('Firebrand Books',5209);
INSERT INTO publisher(name,royalty) VALUES ('Focal Press',4475);
INSERT INTO publisher(name,royalty) VALUES ('Folio Society',3439);
INSERT INTO publisher(name,royalty) VALUES ('Free Press',24);
INSERT INTO publisher(name,royalty) VALUES ('Fulcrum Press',1099);
INSERT INTO publisher(name,royalty) VALUES ('Gaspereau Press',1455);
INSERT INTO publisher(name,royalty) VALUES ('George Newnes',78);
INSERT INTO publisher(name,royalty) VALUES ('Godwit Press',778);
INSERT INTO publisher(name,royalty) VALUES ('Goops Unlimited',742);
INSERT INTO publisher(name,royalty) VALUES ('Grafton',5044);
INSERT INTO publisher(name,royalty) VALUES ('Graywolf Press',3505);
INSERT INTO publisher(name,royalty) VALUES ('Greenery Press',3905);
INSERT INTO publisher(name,royalty) VALUES ('Greenwillow Books',8392);
INSERT INTO publisher(name,royalty) VALUES ('Gregg Press',1368);
INSERT INTO publisher(name,royalty) VALUES ('Grove Press',3925);
INSERT INTO publisher(name,royalty) VALUES ('Hamish Hamilton',2394);
INSERT INTO publisher(name,royalty) VALUES ('Harcourt Assessment',1143);
INSERT INTO publisher(name,royalty) VALUES ('Harcourt Education',909);
INSERT INTO publisher(name,royalty) VALUES ('Harvest House',1744);
INSERT INTO publisher(name,royalty) VALUES ('Hawthorne Books',1758);
INSERT INTO publisher(name,royalty) VALUES ('Hay House',7562);
INSERT INTO publisher(name,royalty) VALUES ('Haynes Manuals',17);
INSERT INTO publisher(name,royalty) VALUES ('Heinemann',2538);
INSERT INTO publisher(name,royalty) VALUES ('Herbert Jenkins',830);
INSERT INTO publisher(name,royalty) VALUES ('Hesperus Press',9934);
INSERT INTO publisher(name,royalty) VALUES ('Heyday Books',5331);
INSERT INTO publisher(name,royalty) VALUES ('Hodder Headline',8141);
INSERT INTO publisher(name,royalty) VALUES ('Hogarth Press',9072);
INSERT INTO publisher(name,royalty) VALUES ('Houghton Mifflin',633);
INSERT INTO publisher(name,royalty) VALUES ('Huffington Post',2184);
INSERT INTO publisher(name,royalty) VALUES ('Humana Press',366);
INSERT INTO publisher(name,royalty) VALUES ('Hutchinson',515);
INSERT INTO publisher(name,royalty) VALUES ('Hyperion',9557);
INSERT INTO publisher(name,royalty) VALUES ('Ignatius Press',4363);
INSERT INTO publisher(name,royalty) VALUES ('Informa Healthcare',2781);
INSERT INTO publisher(name,royalty) VALUES ('Insomniac Press',349);
INSERT INTO publisher(name,royalty) VALUES ('Ishi Press',8021);
INSERT INTO publisher(name,royalty) VALUES ('Island Press',2439);
INSERT INTO publisher(name,royalty) VALUES ('Jarrolds',5979);
INSERT INTO publisher(name,royalty) VALUES ('Jarrolds Publishing',5308);
INSERT INTO publisher(name,royalty) VALUES ('John Lane',1785);
INSERT INTO publisher(name,royalty) VALUES ('John Murray',1737);
INSERT INTO publisher(name,royalty) VALUES ('Karadi Tales',6100);
INSERT INTO publisher(name,royalty) VALUES ('Kensington Books',8631);
INSERT INTO publisher(name,royalty) VALUES ('Kessinger Publishing',2790);
INSERT INTO publisher(name,royalty) VALUES ('Kodansha',6248);
INSERT INTO publisher(name,royalty) VALUES ('Kogan Page',4990);
INSERT INTO publisher(name,royalty) VALUES ('Kumarian Press',7419);
INSERT INTO publisher(name,royalty) VALUES ('Ladybird Books',8267);
INSERT INTO publisher(name,royalty) VALUES ('Leaf Books',8394);
INSERT INTO publisher(name,royalty) VALUES ('Leafwood Publishers',8572);
INSERT INTO publisher(name,royalty) VALUES ('Legend Books',6153);
INSERT INTO publisher(name,royalty) VALUES ('Legend Press',3493);
INSERT INTO publisher(name,royalty) VALUES ('Lethe Press',4661);
INSERT INTO publisher(name,royalty) VALUES ('Libertas Academica',7491);
INSERT INTO publisher(name,royalty) VALUES ('Liberty Fund',6102);
INSERT INTO publisher(name,royalty) VALUES ('Lion Hudson',9383);
INSERT INTO publisher(name,royalty) VALUES ('Lion Publishing',815);
INSERT INTO publisher(name,royalty) VALUES ('Lionel Leventhal',7256);
INSERT INTO publisher(name,royalty) VALUES ('Llewellyn Worldwide',4012);
INSERT INTO publisher(name,royalty) VALUES ('Longman',9732);
INSERT INTO publisher(name,royalty) VALUES ('Lutterworth Press',1333);
INSERT INTO publisher(name,royalty) VALUES ('Macmillan Publishers',23);
INSERT INTO publisher(name,royalty) VALUES ('Mainstream Publishing',2236);
INSERT INTO publisher(name,royalty) VALUES ('Manakin Press',2602);
INSERT INTO publisher(name,royalty) VALUES ('Mandrake Press',1424);
INSERT INTO publisher(name,royalty) VALUES ('Manning Publications',3422);
INSERT INTO publisher(name,royalty) VALUES ('Mapin Publishing',8448);
INSERT INTO publisher(name,royalty) VALUES ('Marshall Cavendish',5749);
INSERT INTO publisher(name,royalty) VALUES ('Marshall Pickering',4633);
INSERT INTO publisher(name,royalty) VALUES ('Matthias Media',4915);
INSERT INTO publisher(name,royalty) VALUES ('Medknow Publications',1301);
INSERT INTO publisher(name,royalty) VALUES ('Mercier Press',6549);
INSERT INTO publisher(name,royalty) VALUES ('Methuen Publishing',5298);
INSERT INTO publisher(name,royalty) VALUES ('Michael Joseph',3764);
INSERT INTO publisher(name,royalty) VALUES ('Microsoft',5748);
INSERT INTO publisher(name,royalty) VALUES ('Microsoft Press',3002);
INSERT INTO publisher(name,royalty) VALUES ('Minerva Press',2250);
INSERT INTO publisher(name,royalty) VALUES ('Mirage Publishing',6810);
INSERT INTO publisher(name,royalty) VALUES ('Modern Library',5944);
INSERT INTO publisher(name,royalty) VALUES ('Myriad Editions',4923);
INSERT INTO publisher(name,royalty) VALUES ('Naiad Press',9168);
INSERT INTO publisher(name,royalty) VALUES ('Nauka',8648);
INSERT INTO publisher(name,royalty) VALUES ('Newnes',6892);
INSERT INTO publisher(name,royalty) VALUES ('Nonesuch Press',6475);
INSERT INTO publisher(name,royalty) VALUES ('Noontide Press',9378);
INSERT INTO publisher(name,royalty) VALUES ('Nosy Crow',7210);
INSERT INTO publisher(name,royalty) VALUES ('Oberon Books',6505);
INSERT INTO publisher(name,royalty) VALUES ('Orchard Books',8024);
INSERT INTO publisher(name,royalty) VALUES ('Orion Books',826);
INSERT INTO publisher(name,royalty) VALUES ('Osprey Publishing',1299);
INSERT INTO publisher(name,royalty) VALUES ('Other Press',1952);
INSERT INTO publisher(name,royalty) VALUES ('Packt Publishing',9893);
INSERT INTO publisher(name,royalty) VALUES ('Palgrave Macmillan',9829);
INSERT INTO publisher(name,royalty) VALUES ('Pan Books',4888);
INSERT INTO publisher(name,royalty) VALUES ('Papadakis Publisher',6538);
INSERT INTO publisher(name,royalty) VALUES ('Parachute Publishing',4791);
INSERT INTO publisher(name,royalty) VALUES ('Parragon',7139);
INSERT INTO publisher(name,royalty) VALUES ('Pathfinder Press',4698);
INSERT INTO publisher(name,royalty) VALUES ('Paulist Press',6486);
INSERT INTO publisher(name,royalty) VALUES ('Pavilion Books',2392);
INSERT INTO publisher(name,royalty) VALUES ('Pearson Education',7587);
INSERT INTO publisher(name,royalty) VALUES ('Penguin Books',7521);
INSERT INTO publisher(name,royalty) VALUES ('Penguin Group',9309);
INSERT INTO publisher(name,royalty) VALUES ('Persephone Books',3075);
INSERT INTO publisher(name,royalty) VALUES ('Peter Lang',5874);
INSERT INTO publisher(name,royalty) VALUES ('Phaidon Press',1528);
INSERT INTO publisher(name,royalty) VALUES ('Philtrum Press',648);
INSERT INTO publisher(name,royalty) VALUES ('Picador',4409);
INSERT INTO publisher(name,royalty) VALUES ('Pluto Press',3670);
INSERT INTO publisher(name,royalty) VALUES ('Point Blank',9648);
INSERT INTO publisher(name,royalty) VALUES ('Policy Press',4567);
INSERT INTO publisher(name,royalty) VALUES ('Polity',4335);
INSERT INTO publisher(name,royalty) VALUES ('Practical Action',5102);
INSERT INTO publisher(name,royalty) VALUES ('Prentice Hall',9491);
INSERT INTO publisher(name,royalty) VALUES ('Prime Books',4131);
INSERT INTO publisher(name,royalty) VALUES ('Profile Books',1583);
INSERT INTO publisher(name,royalty) VALUES ('Progress Publishers',1733);
INSERT INTO publisher(name,royalty) VALUES ('Prometheus Books',5943);
INSERT INTO publisher(name,royalty) VALUES ('Puffin Books',1311);
INSERT INTO publisher(name,royalty) VALUES ('Que Publishing',423);
INSERT INTO publisher(name,royalty) VALUES ('Quebecor',3225);
INSERT INTO publisher(name,royalty) VALUES ('Quirk Books',1533);
INSERT INTO publisher(name,royalty) VALUES ('Random House',4416);
INSERT INTO publisher(name,royalty) VALUES ('Redstone Press',9937);
INSERT INTO publisher(name,royalty) VALUES ('Reed Elsevier',5250);
INSERT INTO publisher(name,royalty) VALUES ('Reed Publishing',3431);
INSERT INTO publisher(name,royalty) VALUES ('Riverhead Books',8782);
INSERT INTO publisher(name,royalty) VALUES ('Robson Books',7477);
INSERT INTO publisher(name,royalty) VALUES ('Rodopi',6772);
INSERT INTO publisher(name,royalty) VALUES ('Routledge',2014);
INSERT INTO publisher(name,royalty) VALUES ('Salt Publishing',5322);
INSERT INTO publisher(name,royalty) VALUES ('Sams Publishing',3632);
INSERT INTO publisher(name,royalty) VALUES ('Samuel French',5303);
INSERT INTO publisher(name,royalty) VALUES ('Schocken Books',3960);
INSERT INTO publisher(name,royalty) VALUES ('Scholastic Press',9577);
INSERT INTO publisher(name,royalty) VALUES ('Scribner',7521);
INSERT INTO publisher(name,royalty) VALUES ('Seagull Books',5821);
INSERT INTO publisher(name,royalty) VALUES ('Serif',2852);
INSERT INTO publisher(name,royalty) VALUES ('Shambhala Publications',7195);
INSERT INTO publisher(name,royalty) VALUES ('Shire Books',3175);
INSERT INTO publisher(name,royalty) VALUES ('Signet Books',6660);
INSERT INTO publisher(name,royalty) VALUES ('Sounds True',1841);
INSERT INTO publisher(name,royalty) VALUES ('Sourcebooks',6234);
INSERT INTO publisher(name,royalty) VALUES ('Spinsters Ink',1183);
INSERT INTO publisher(name,royalty) VALUES ('Springer Verlag',6198);
INSERT INTO publisher(name,royalty) VALUES ('Summerwild Productions',3065);
INSERT INTO publisher(name,royalty) VALUES ('Summit Media',1703);
INSERT INTO publisher(name,royalty) VALUES ('Tachyon Publications',5177);
INSERT INTO publisher(name,royalty) VALUES ('Tammi',3548);
INSERT INTO publisher(name,royalty) VALUES ('Target Books',3295);
INSERT INTO publisher(name,royalty) VALUES ('Tartarus Press',4492);
INSERT INTO publisher(name,royalty) VALUES ('Taunton Press',7117);
INSERT INTO publisher(name,royalty) VALUES ('Thomas Nelson',4729);
INSERT INTO publisher(name,royalty) VALUES ('Ticonderoga Publications',1418);
INSERT INTO publisher(name,royalty) VALUES ('Times Books',9905);
INSERT INTO publisher(name,royalty) VALUES ('Titan Books',7663);
INSERT INTO publisher(name,royalty) VALUES ('Tor Books',7969);
INSERT INTO publisher(name,royalty) VALUES ('Triangle Books',9315);
INSERT INTO publisher(name,royalty) VALUES ('Troubador Press',428);
INSERT INTO publisher(name,royalty) VALUES ('Tupelo Press',8358);
INSERT INTO publisher(name,royalty) VALUES ('Tuttle Publishing',686);
INSERT INTO publisher(name,royalty) VALUES ('Twelveheads Press',9652);
INSERT INTO publisher(name,royalty) VALUES ('Usborne Publishing',784);
INSERT INTO publisher(name,royalty) VALUES ('Valancourt Books',2848);
INSERT INTO publisher(name,royalty) VALUES ('Velazquez Press',2118);
INSERT INTO publisher(name,royalty) VALUES ('Verso Books',89);
INSERT INTO publisher(name,royalty) VALUES ('Viking Press',1905);
INSERT INTO publisher(name,royalty) VALUES ('Vintage Books',4380);
INSERT INTO publisher(name,royalty) VALUES ('Virago Press',6629);
INSERT INTO publisher(name,royalty) VALUES ('Virgin Publishing',9154);
INSERT INTO publisher(name,royalty) VALUES ('Voyager Books',8113);
INSERT INTO publisher(name,royalty) VALUES ('Wildside Press',358);
INSERT INTO publisher(name,royalty) VALUES ('Windgate Press',5663);
INSERT INTO publisher(name,royalty) VALUES ('Wisdom Publications',5520);
INSERT INTO publisher(name,royalty) VALUES ('Witherby Seamanship',2950);
INSERT INTO publisher(name,royalty) VALUES ('Wolters Kluwer',8601);
INSERT INTO publisher(name,royalty) VALUES ('Woodhead Publishing',8778);
INSERT INTO publisher(name,royalty) VALUES ('Wordfarm',2222);
INSERT INTO publisher(name,royalty) VALUES ('Workman Publishing',1332);
INSERT INTO publisher(name,royalty) VALUES ('Wrox Press',4089);
INSERT INTO publisher(name,royalty) VALUES ('Xoanon Publishing',5957);
INSERT INTO publisher(name,royalty) VALUES ('Zed Books',2882);
INSERT INTO publisher(name,royalty) VALUES ('Zondervan',3833);
